// <auto-generated/>
#nullable enable

using System.Linq.Expressions;
using BonefireCRM.Domain.Entities;
using BonefireCRM.Domain.DTOs.Activity.Task;

namespace BonefireCRM.SourceGenerator;

public static partial class AssignmentQueryExpressions
{
    public static Expression<Func<Assignment, bool>> Filter(GetAllTasksDTO filterCriteria)
    {
        return x =>
            (!filterCriteria.Id.HasValue || x.Id == filterCriteria.Id)
            && (string.IsNullOrEmpty(filterCriteria.Subject) || x.Subject == filterCriteria.Subject)
            && (string.IsNullOrEmpty(filterCriteria.Description) || x.Description == filterCriteria.Description)
            && (!filterCriteria.DueDate.HasValue || x.DueDate == filterCriteria.DueDate)
            && (!filterCriteria.IsCompleted.HasValue || x.IsCompleted == filterCriteria.IsCompleted)
            && (!filterCriteria.UserId.HasValue || x.UserId == filterCriteria.UserId)
            && (!filterCriteria.ContactId.HasValue || x.ContactId == filterCriteria.ContactId)
            && (!filterCriteria.CompanyId.HasValue || x.CompanyId == filterCriteria.CompanyId)
            && (!filterCriteria.DealId.HasValue || x.DealId == filterCriteria.DealId)
            ;
    }

    public static Expression<Func<Assignment, object>> Sort(string sortCriteria)
    {
        return sortCriteria switch
        {
            nameof(Assignment.Id) => x => x.Id,
            nameof(Assignment.Subject) => x => x.Subject,
            nameof(Assignment.Description) => x => x.Description,
            nameof(Assignment.DueDate) => x => x.DueDate,
            nameof(Assignment.IsCompleted) => x => x.IsCompleted,
            nameof(Assignment.UserId) => x => x.UserId,
            nameof(Assignment.ContactId) => x => x.ContactId,
            nameof(Assignment.CompanyId) => x => x.CompanyId,
            nameof(Assignment.DealId) => x => x.DealId,
            _ => throw new ArgumentException("no default property for generation")
        };
    }
}