// <auto-generated/>
#nullable enable

using System.Linq.Expressions;
using BonefireCRM.Domain.Entities;
using BonefireCRM.Domain.DTOs.Contact;

namespace BonefireCRM.SourceGenerator;

public static partial class ContactQueryExpressions
{
    public static Expression<Func<Contact, bool>> Filter(GetAllContactsDTO filterCriteria)
    {
        return x =>
            (!filterCriteria.Id.HasValue || x.Id == filterCriteria.Id)
            && (string.IsNullOrEmpty(filterCriteria.FirstName) || x.FirstName == filterCriteria.FirstName)
            && (string.IsNullOrEmpty(filterCriteria.LastName) || x.LastName == filterCriteria.LastName)
            && (string.IsNullOrEmpty(filterCriteria.Email) || x.Email == filterCriteria.Email)
            && (string.IsNullOrEmpty(filterCriteria.PhoneNumber) || x.PhoneNumber == filterCriteria.PhoneNumber)
            && (string.IsNullOrEmpty(filterCriteria.JobRole) || x.JobRole == filterCriteria.JobRole)
            && (!filterCriteria.UserId.HasValue || x.UserId == filterCriteria.UserId)
            && (!filterCriteria.LifecycleStageId.HasValue || x.LifecycleStageId == filterCriteria.LifecycleStageId)
            && (!filterCriteria.CompanyId.HasValue || x.CompanyId == filterCriteria.CompanyId)
            ;
    }

    public static Expression<Func<Contact, object>> Sort(string sortCriteria)
    {
        return sortCriteria switch
        {
            nameof(Contact.Id) => x => x.Id,
            nameof(Contact.FirstName) => x => x.FirstName,
            nameof(Contact.LastName) => x => x.LastName,
            nameof(Contact.Email) => x => x.Email,
            nameof(Contact.PhoneNumber) => x => x.PhoneNumber,
            nameof(Contact.JobRole) => x => x.JobRole,
            nameof(Contact.UserId) => x => x.UserId,
            nameof(Contact.LifecycleStageId) => x => x.LifecycleStageId,
            nameof(Contact.CompanyId) => x => x.CompanyId,
            _ => throw new ArgumentException("no default property for generation")
        };
    }
}