// <auto-generated/>
#nullable enable

using System.Linq.Expressions;
using BonefireCRM.Domain.Entities;
using BonefireCRM.Domain.DTOs.User;

namespace BonefireCRM.SourceGenerator;

public static partial class UserQueryExpressions
{
    public static Expression<Func<User, bool>> Filter(GetAllUsersDTO filterCriteria)
    {
        return x =>
            (!filterCriteria.Id.HasValue || x.Id == filterCriteria.Id)
            && (!filterCriteria.RegisterId.HasValue || x.RegisterId == filterCriteria.RegisterId)
            && (string.IsNullOrEmpty(filterCriteria.UserName) || x.UserName == filterCriteria.UserName)
            && (string.IsNullOrEmpty(filterCriteria.Email) || x.Email == filterCriteria.Email)
            && (string.IsNullOrEmpty(filterCriteria.FirstName) || x.FirstName == filterCriteria.FirstName)
            && (string.IsNullOrEmpty(filterCriteria.LastName) || x.LastName == filterCriteria.LastName)
            ;
    }

    public static Expression<Func<User, object>> Sort(string sortCriteria)
    {
        return sortCriteria switch
        {
            nameof(User.Id) => x => x.Id,
            nameof(User.RegisterId) => x => x.RegisterId,
            nameof(User.UserName) => x => x.UserName,
            nameof(User.Email) => x => x.Email,
            nameof(User.FirstName) => x => x.FirstName,
            nameof(User.LastName) => x => x.LastName,
            _ => throw new ArgumentException("no default property for generation")
        };
    }
}