// <auto-generated/>
#nullable enable

using System.Linq.Expressions;
using BonefireCRM.Domain.Entities;
using BonefireCRM.Domain.DTOs.Activity.Call;

namespace BonefireCRM.SourceGenerator;

public static partial class CallQueryExpressions
{
    public static Expression<Func<Call, bool>> Filter(GetAllCallsDTO filterCriteria)
    {
        return x =>
            (!filterCriteria.Id.HasValue || x.Id == filterCriteria.Id)
            && (!filterCriteria.CallTime.HasValue || x.CallTime == filterCriteria.CallTime)
            && (!filterCriteria.Duration.HasValue || x.Duration == filterCriteria.Duration)
            && (string.IsNullOrEmpty(filterCriteria.Notes) || x.Notes == filterCriteria.Notes)
            && (!filterCriteria.UserId.HasValue || x.UserId == filterCriteria.UserId)
            && (!filterCriteria.ContactId.HasValue || x.ContactId == filterCriteria.ContactId)
            && (!filterCriteria.CompanyId.HasValue || x.CompanyId == filterCriteria.CompanyId)
            && (!filterCriteria.DealId.HasValue || x.DealId == filterCriteria.DealId)
            ;
    }

    public static Expression<Func<Call, object>> Sort(string sortCriteria)
    {
        return sortCriteria switch
        {
            nameof(Call.Id) => x => x.Id,
            nameof(Call.CallTime) => x => x.CallTime,
            nameof(Call.Duration) => x => x.Duration,
            nameof(Call.Notes) => x => x.Notes,
            nameof(Call.UserId) => x => x.UserId,
            nameof(Call.ContactId) => x => x.ContactId,
            nameof(Call.CompanyId) => x => x.CompanyId,
            nameof(Call.DealId) => x => x.DealId,
            _ => throw new ArgumentException("no default property for generation")
        };
    }
}