// <auto-generated/>
#nullable enable

using System.Linq.Expressions;
using BonefireCRM.Domain.Entities;
using BonefireCRM.Domain.DTOs.Pipeline;

namespace BonefireCRM.SourceGenerator;

public static partial class PipelineQueryExpressions
{
    public static Expression<Func<Pipeline, bool>> Filter(GetAllPipelinesDTO filterCriteria)
    {
        return x =>
            (!filterCriteria.Id.HasValue || x.Id == filterCriteria.Id)
            && (string.IsNullOrEmpty(filterCriteria.Name) || x.Name == filterCriteria.Name)
            && (!filterCriteria.IsDefault.HasValue || x.IsDefault == filterCriteria.IsDefault)
            ;
    }

    public static Expression<Func<Pipeline, object>> Sort(string sortCriteria)
    {
        return sortCriteria switch
        {
            nameof(Pipeline.Id) => x => x.Id,
            nameof(Pipeline.Name) => x => x.Name,
            nameof(Pipeline.IsDefault) => x => x.IsDefault,
            _ => throw new ArgumentException("no default property for generation")
        };
    }
}