// <auto-generated/>
#nullable enable

using System.Linq.Expressions;
using BonefireCRM.Domain.Entities;
using BonefireCRM.Domain.DTOs.Company;

namespace BonefireCRM.SourceGenerator;

public static partial class CompanyQueryExpressions
{
    public static Expression<Func<Company, bool>> Filter(GetAllCompaniesDTO filterCriteria)
    {
        return x =>
            (!filterCriteria.Id.HasValue || x.Id == filterCriteria.Id)
            && (string.IsNullOrEmpty(filterCriteria.Name) || x.Name == filterCriteria.Name)
            && (string.IsNullOrEmpty(filterCriteria.Industry) || x.Industry == filterCriteria.Industry)
            && (string.IsNullOrEmpty(filterCriteria.Address) || x.Address == filterCriteria.Address)
            && (string.IsNullOrEmpty(filterCriteria.PhoneNumber) || x.PhoneNumber == filterCriteria.PhoneNumber)
            ;
    }

    public static Expression<Func<Company, object>> Sort(string sortCriteria)
    {
        return sortCriteria switch
        {
            nameof(Company.Id) => x => x.Id,
            nameof(Company.Name) => x => x.Name,
            nameof(Company.Industry) => x => x.Industry,
            nameof(Company.Address) => x => x.Address,
            nameof(Company.PhoneNumber) => x => x.PhoneNumber,
            _ => throw new ArgumentException("no default property for generation")
        };
    }
}