// <auto-generated/>
#nullable enable

using System.Linq.Expressions;
using BonefireCRM.Domain.Entities;
using BonefireCRM.Domain.DTOs.Deal;

namespace BonefireCRM.SourceGenerator;

public static partial class DealQueryExpressions
{
    public static Expression<Func<Deal, bool>> Filter(GetAllDealsDTO filterCriteria)
    {
        return x =>
            (!filterCriteria.Id.HasValue || x.Id == filterCriteria.Id)
            && (string.IsNullOrEmpty(filterCriteria.Title) || x.Title == filterCriteria.Title)
            && (!filterCriteria.Amount.HasValue || x.Amount == filterCriteria.Amount)
            && (!filterCriteria.ExpectedCloseDate.HasValue || x.ExpectedCloseDate == filterCriteria.ExpectedCloseDate)
            && (!filterCriteria.PipelineStageId.HasValue || x.PipelineStageId == filterCriteria.PipelineStageId)
            && (!filterCriteria.CompanyId.HasValue || x.CompanyId == filterCriteria.CompanyId)
            && (!filterCriteria.PrimaryContactId.HasValue || x.PrimaryContactId == filterCriteria.PrimaryContactId)
            && (!filterCriteria.UserId.HasValue || x.UserId == filterCriteria.UserId)
            ;
    }

    public static Expression<Func<Deal, object>> Sort(string sortCriteria)
    {
        return sortCriteria switch
        {
            nameof(Deal.Id) => x => x.Id,
            nameof(Deal.Title) => x => x.Title,
            nameof(Deal.Amount) => x => x.Amount,
            nameof(Deal.ExpectedCloseDate) => x => x.ExpectedCloseDate,
            nameof(Deal.PipelineStageId) => x => x.PipelineStageId,
            nameof(Deal.CompanyId) => x => x.CompanyId,
            nameof(Deal.PrimaryContactId) => x => x.PrimaryContactId,
            nameof(Deal.UserId) => x => x.UserId,
            _ => throw new ArgumentException("no default property for generation")
        };
    }
}