// <auto-generated/>
#nullable enable

using System.Linq.Expressions;
using BonefireCRM.Domain.Entities;
using BonefireCRM.Domain.DTOs.LifeCycleStage;

namespace BonefireCRM.SourceGenerator;

public static partial class LifecycleStageQueryExpressions
{
    public static Expression<Func<LifecycleStage, bool>> Filter(GetAllLifecycleStagesDTO filterCriteria)
    {
        return x =>
            (!filterCriteria.Id.HasValue || x.Id == filterCriteria.Id)
            && (string.IsNullOrEmpty(filterCriteria.Name) || x.Name == filterCriteria.Name)
            ;
    }

    public static Expression<Func<LifecycleStage, object>> Sort(string sortCriteria)
    {
        return sortCriteria switch
        {
            nameof(LifecycleStage.Id) => x => x.Id,
            nameof(LifecycleStage.Name) => x => x.Name,
            _ => throw new ArgumentException("no default property for generation")
        };
    }
}