// <auto-generated/>
#nullable enable

using System.Linq.Expressions;
using BonefireCRM.Domain.Entities;
using BonefireCRM.Domain.DTOs.PipelineStage;

namespace BonefireCRM.SourceGenerator;

public static partial class PipelineStageQueryExpressions
{
    public static Expression<Func<PipelineStage, bool>> Filter(GetAllPipelineStagesDTO filterCriteria)
    {
        return x =>
            (!filterCriteria.Id.HasValue || x.Id == filterCriteria.Id)
            && (!filterCriteria.PipelineId.HasValue || x.PipelineId == filterCriteria.PipelineId)
            && (string.IsNullOrEmpty(filterCriteria.Name) || x.Name == filterCriteria.Name)
            && (!filterCriteria.OrderIndex.HasValue || x.OrderIndex == filterCriteria.OrderIndex)
            && (!filterCriteria.Status.HasValue || x.Status == filterCriteria.Status)
            ;
    }

    public static Expression<Func<PipelineStage, object>> Sort(string sortCriteria)
    {
        return sortCriteria switch
        {
            nameof(PipelineStage.Id) => x => x.Id,
            nameof(PipelineStage.PipelineId) => x => x.PipelineId,
            nameof(PipelineStage.Name) => x => x.Name,
            nameof(PipelineStage.OrderIndex) => x => x.OrderIndex,
            nameof(PipelineStage.Status) => x => x.Status,
            _ => throw new ArgumentException("no default property for generation")
        };
    }
}