// <auto-generated/>
#nullable enable

using System.Linq.Expressions;
using BonefireCRM.Domain.Entities;
using BonefireCRM.Domain.DTOs.Activity.Meeting;

namespace BonefireCRM.SourceGenerator;

public static partial class MeetingQueryExpressions
{
    public static Expression<Func<Meeting, bool>> Filter(GetAllMeetingsDTO filterCriteria)
    {
        return x =>
            (!filterCriteria.Id.HasValue || x.Id == filterCriteria.Id)
            && (string.IsNullOrEmpty(filterCriteria.Subject) || x.Subject == filterCriteria.Subject)
            && (string.IsNullOrEmpty(filterCriteria.Notes) || x.Notes == filterCriteria.Notes)
            && (!filterCriteria.StartTime.HasValue || x.StartTime == filterCriteria.StartTime)
            && (!filterCriteria.EndTime.HasValue || x.EndTime == filterCriteria.EndTime)
            && (!filterCriteria.UserId.HasValue || x.UserId == filterCriteria.UserId)
            && (!filterCriteria.ContactId.HasValue || x.ContactId == filterCriteria.ContactId)
            && (!filterCriteria.CompanyId.HasValue || x.CompanyId == filterCriteria.CompanyId)
            && (!filterCriteria.DealId.HasValue || x.DealId == filterCriteria.DealId)
            ;
    }

    public static Expression<Func<Meeting, object>> Sort(string sortCriteria)
    {
        return sortCriteria switch
        {
            nameof(Meeting.Id) => x => x.Id,
            nameof(Meeting.Subject) => x => x.Subject,
            nameof(Meeting.Notes) => x => x.Notes,
            nameof(Meeting.StartTime) => x => x.StartTime,
            nameof(Meeting.EndTime) => x => x.EndTime,
            nameof(Meeting.UserId) => x => x.UserId,
            nameof(Meeting.ContactId) => x => x.ContactId,
            nameof(Meeting.CompanyId) => x => x.CompanyId,
            nameof(Meeting.DealId) => x => x.DealId,
            _ => throw new ArgumentException("no default property for generation")
        };
    }
}