// <auto-generated/>
#nullable enable

using System.Linq.Expressions;
using BonefireCRM.Domain.Entities;
using BonefireCRM.Domain.DTOs.DealParticipantRole;

namespace BonefireCRM.SourceGenerator;

public static partial class DealParticipantRoleQueryExpressions
{
    public static Expression<Func<DealParticipantRole, bool>> Filter(GetAllDealParticipantRolesDTO filterCriteria)
    {
        return x =>
            (!filterCriteria.Id.HasValue || x.Id == filterCriteria.Id)
            && (!filterCriteria.RegisteredByUserId.HasValue || x.RegisteredByUserId == filterCriteria.RegisteredByUserId)
            && (string.IsNullOrEmpty(filterCriteria.Name) || x.Name == filterCriteria.Name)
            && (string.IsNullOrEmpty(filterCriteria.Description) || x.Description == filterCriteria.Description)
            ;
    }

    public static Expression<Func<DealParticipantRole, object>> Sort(string sortCriteria)
    {
        return sortCriteria switch
        {
            nameof(DealParticipantRole.Id) => x => x.Id,
            nameof(DealParticipantRole.RegisteredByUserId) => x => x.RegisteredByUserId,
            nameof(DealParticipantRole.Name) => x => x.Name,
            nameof(DealParticipantRole.Description) => x => x.Description,
            _ => throw new ArgumentException("no default property for generation")
        };
    }
}